### ISSUE TITLE
Error when trying to run examples

### ISSUE THREAD

**Issue by jsnells1** [sccn/labstreaminglayer#240]
Hello,

I'm probably doing something wrong, but I'm trying to run the java examples and got the following error after doing what the README says:

Exception in thread "main" java.lang.UnsatisfiedLinkError: The specified module could not be found.

	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:263)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
	at edu.ucsd.sccn.LSL.<clinit>(LSL.java:1098)
	at edu.ucsd.sccn.LSL$StreamInfo.<init>(LSL.java:160)
	at test.Main.main(Main.java:11)

I'm doing this for a research project so I'm a little new to all of this.

**Comment by mgrivich** [comment]
Did you follow the instructions at 
https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl-Java ?

**Comment by mgrivich** [comment]
Sorry. I see now that you said that you were following the readme. Are 
you on a 64 bit system? Where did you put liblsl64.dll? There error 
indicates that this dll is not found.

**Comment by jsnells1** [comment]
I have it in LSL/liblsl-Java/src/
I had it in another place and it couldn't find the dll and told me to move it to this location. That's when I got this error.

**Comment by jsnells1** [comment]
Well I think I built the project wrong so I'm redoing that and am now getting errors.

error C2065: '__deprecated__': undeclared identifier [labstreaminglayer-master\labstreaminglayer-master\build\lsl_Release\CMakeFiles\CMakeTmp\cmTC_d1f4c.vcxproj]

error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [labstreaminglayer-master\labstreaminglayer-master\build\lsl_Release\CMakeFiles\CMakeTmp\cmTC_d1f4c.vcxproj]

error C2448: '__attribute__': function-style initializer appears to be a function definition [labstreaminglayer-master\labstreaminglayer-master\build\lsl_Release\CMakeFiles\CMakeTmp\cmTC_d1f4c.vcxproj]

**Comment by tstenner** [comment]
Could you attach the whole build log? If Github doesn't allow attachments, [Github Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) should work.

**Comment by mgrivich** [comment]
liblsl64.dll should be in liblsl-Java, not liblsl-Java/src

**Comment by mgrivich** [comment]
The CMake build is new and the kinks have not been worked out yet. I'm sure that Tristan would appreciate more detailed bug reports to help fix the issues. However, for now note that there are functional projects for the various platforms at https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl/project  I think you are on windows, and I'd recommend vs2013.

**Comment by jsnells1** [comment]
I had the liblsl64.dll in liblsl-Java and it said it couldn't find it. One of the suggested paths was in the /src folder so I moved it there. It could find it but then gave me the error in the original post. I can post the pastebin when I'm back home tonight.

**Comment by mgrivich** [comment]
Are you following these instructions exactly?:

```
To compile and run the examples:
Download jna-4.2.2.jar (http://central.maven.org/maven2/net/java/dev/jna/jna/4.2.2/jna-4.2.2.jar) 
to LSL/liblsl-Java.

Build the LSL library (liblsl64.dll, for example) for your system, and copy it to LSL/liblsl-Java

LSL/liblsl-Java$ javac -cp jna-4.2.2.jar src/edu/ucsd/sccn/LSL.java src/examples/SendData.java 
where SendData.java is the example that you are interested in.

LSL/liblsl-Java$ java -Djna.nosys=true -cp "jna-4.2.2.jar:src" examples.SendData (on Linux)
LSL/liblsl-Java> java -cp "jna-4.2.2.jar;src" examples.SendData (on Windows, yes the : changes to a ;)
```

Note the little details like you should be in the LSL/liblsl-Java folder when typing commands.

**Comment by jsnells1** [comment]
[CMakeError.log](https://github.com/sccn/labstreaminglayer/files/1400646/CMakeError.log)
[CMakeOutput.log](https://github.com/sccn/labstreaminglayer/files/1400647/CMakeOutput.log)

Here are the Error and Output logs.

As to mgrivich's question, yes I followed all those directions. To be honest, I don't remember how I got the liblsl64.dll but I never compiled the build as instructed in INSTALL.MD. So what I'm doing now is trying to build that correctly but I'm getting errors with that, too.

**Comment by cboulay** [comment]
Are the errors you attached from trying to follow INSTALL.MD or from something else?

If they are from something else then can you please tell us what trouble you're having with INSTALL.MD? We'd really like to make it more useful generally so any feedback at all is wanted.

**Comment by jsnells1** [comment]
That is from INSTALL.MD

I'm using the lslbuild.py script. I've tried it with both VS2015 and VS2017. I'm also trying to build it without the apps, just need LSL.

**Comment by tstenner** [comment]
Thank you for the logs. I'm on the road until Tuesday so I haven't looked yet at all the details, but I might have some ideas.
Firstly, the default configuration builds two apps you might not need (see #241), you can disable them with `-DLSLAPPS_LabRecorder=Off` and `-DLSLAPPS_XDFBrowser=Off`. Also, with multiple MSVC versions installed, CMake might pick up the wrong. You can specify a version with the `--generator="Visual Studio 15 2017 Win64“` argument to lslbuild.py (before running it, you should delete the build folder).

**Comment by jsnells1** [comment]
@tstenner Thank you! This basically worked. I tried setting those switches but they weren't working so I went into the CMakeList and disabled them manually which worked. I'm going to try to specify Win64 when I get home because it created a 32-bit version. It also only created Debug dlls when I specified Release so I'll look into that when I get home, as well.

**Comment by jsnells1** [comment]
With the help of Issue #241 I've seemed to compile everything correctly and now have the 64bit dlls. Thanks for the help! Now I can test and see how everything goes.
