### ISSUE TITLE
ModuleNotFoundError: No module named 'serial'

### ISSUE THREAD

**Issue by digitalgreentea** [sccn/labstreaminglayer#288]
When I run: 

python openbci_lsl.py --stream

in CMD it displays the following error:

Traceback (most recent call last):
  File "openbci_lsl.py", line 25, in <module>
    import lib.streamerlsl as streamerlsl
  File "C:\Program Files\MATLAB\OpenBCI_LSL\lib\streamerlsl.py", line 20, in <module>
    import lib.open_bci_v3 as bci
  File "C:\Program Files\MATLAB\OpenBCI_LSL\lib\open_bci_v3.py", line 19, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'

Does anyone know how to solve this?

**Comment by cboulay** [comment]
OpenBCI_LSL is not LSL. We don't have anything to do with that code.

Anyway, you can probably fix it by installing pyserial. `pip install pyserial`
